apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: javaapp
  namespace: argocd

  annotations:
    argocd-image-updater.argoproj.io/image-list: app=docker89781/sample-app

    argocd-image-updater.argoproj.io/app.update-strategy: newest-build

    argocd-image-updater.argoproj.io/app.allow-tags: regexp:^[0-9]+$

    argocd-image-updater.argoproj.io/app.helm.image-name: image.repository

    argocd-image-updater.argoproj.io/app.helm.image-tag: image.tag

    argocd-image-updater.argoproj.io/write-back-method: git

spec:
  project: default

  source:
    repoURL: https://github.com/devopsclouds/k8-manifests.git

    targetRevision: main

    path:  helm-dependency

    helm:
      valueFiles:
      - ../apps/javaapp-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
