apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: javaapp
  namespace: argocd

  annotations:
    argocd-image-updater.argoproj.io/image-list: app=docker89781/sample-app
    
    # 2. Chronological Strategy for Build Numbers
    argocd-image-updater.argoproj.io/myapp.update-strategy: latest
    
    # 3. Match Pattern (e.g., build-1, build-204, build-1049)
    argocd-image-updater.argoproj.io/myapp.allow-tags: regexp:^build-\d+$
    
    # 4. Bind to your Helm values keys
    argocd-image-updater.argoproj.io/myapp.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/myapp.helm.image-tag: image.tag
    
    # 5. Git Write-Back Configuration
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main #

spec:
  project: default

  source:
    repoURL: https://github.com/devopsclouds/k8-manifests.git

    targetRevision: main

    path:  helm-dependency

    helm:
      valueFiles:
      - ../apps/javaapp-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
